# Generated by Django 5.2.8 on 2025-11-10 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='join_in',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
