# Generated by Django 5.2.8 on 2025-11-11 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product_remove_student_age_remove_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cake', 'Cake'), ('Soft Drink', 'Soft Drink')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.CharField(choices=[('Ebene', 'Ebene')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AmountInserted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes_200', models.PositiveIntegerField(default=0)),
                ('notes_100', models.PositiveIntegerField(default=0)),
                ('notes_50', models.PositiveIntegerField(default=0)),
                ('notes_25', models.PositiveIntegerField(default=0)),
                ('coins_20', models.PositiveIntegerField(default=0)),
                ('coins_10', models.PositiveIntegerField(default=0)),
                ('coins_5', models.PositiveIntegerField(default=0)),
                ('coins_1', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes_200', models.PositiveIntegerField(default=0)),
                ('notes_100', models.PositiveIntegerField(default=0)),
                ('notes_50', models.PositiveIntegerField(default=0)),
                ('notes_25', models.PositiveIntegerField(default=0)),
                ('coins_20', models.PositiveIntegerField(default=0)),
                ('coins_10', models.PositiveIntegerField(default=0)),
                ('coins_5', models.PositiveIntegerField(default=0)),
                ('coins_1', models.PositiveIntegerField(default=0)),
                ('total_return', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_inserted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.student')),
            ],
        ),
    ]
